name: test pipeline

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

env:
  NXF_ANSI_LOG: false

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        NXF_VER:
          - "21.10.3"
          - "latest-everything"

    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v3

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v1
        with:
          version: "${{ matrix.NXF_VER }}"

      - name: Run pipeline with test data
        run: |
          nextflow run ${GITHUB_WORKSPACE} --output_dir results
